version: '3.8'

services:
  echo-server:
    build:
      context: .
      dockerfile: Dockerfile.echo
    ports:
      - "5001:5001"
    volumes:
      - ./data:/data  # Ensure the database is accessible

  storage-server:
    build:
      context: .
      dockerfile: Dockerfile.storage
    ports:
      - "5002:5002"
    volumes:
      - ./data:/data  # Ensure the database is accessible

