version: '3.8'

services:
  echo2_server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - APP_ENV=production
    container_name: echo2_server

  storage2_server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    environment:
      - APP_ENV=production
    container_name: storage2_server

