version: '3.8'

services:
  echo2_server:
    build:
      context: .
      dockerfile: Dockerfile.echo2
    ports:
      - "5001:5001"
    environment:
      - APP_ENV=production
    deploy:
      resources:
        limits:
          memory: 512M
    container_name: echo2_server

  storage2_server:
    build:
      context: .
      dockerfile: Dockerfile.storage2
    ports:
      - "5002:5002"
    environment:
      - APP_ENV=production
    deploy:
      resources:
        limits:
          memory: 512M
    container_name: storage2_server

networks:
  default:
    name: echo-network
    driver: bridge

